# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false

r:
  - 3.3
  - oldrel
  - release
  - devel

repos:
  docker: https://r.docker.stat.auckland.ac.nz

r_github_packages:
  - dkahle/ggmap

addons:
  apt:
    update: true
    sources:
      - ubuntugis-unstable: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

