# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false

matrix:
  include:
    - os: linux
      r: 3.3
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
  allow_failures:
    - r: 3.3

repos:
  docker: https://r.docker.stat.auckland.ac.nz

r_github_packages:
  - dkahle/ggmap
  - iNZightVIT/iNZightPlots@dev

addons:
  apt:
    update: true
    sources:
      - ubuntugis-unstable: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
